-- N.B. this contains Postgres specific bullshit
-- You know how it is.

CREATE TABLE comics (
  id SERIAL PRIMARY KEY,
  title text,
  image text,
  alt_image text
);

CREATE TABLE associations (
  comic_id integer REFERENCES comics(id),
  theme_id integer REFERENCES themes(id)
);
CREATE INDEX ON associations (comic_id);
CREATE INDEX ON associations (theme_id);

CREATE TABLE themes (
  id SERIAL PRIMARY KEY,
  name varchar(50)
);

INSERT INTO comics (title, image) VALUES
  ('Attack your lady harder 6GD', 'tEsVbpUhqZDCUoeLJhkjqg.jpg'),
  ('lusty', 'xwGOOr8xO-9fzAfKyMk4Vw.png'),
  ('get em che4p right now [yes they will help \;-)', 'yojktWF-WqLxnMvJsUlRjA.png'),
  ('Easy Way To Make Money With Your Digital Camera', '3aGLWz4bu57Mzzybk5C3CA.jpg'),
  ('Re: Horatio, some tact', 'iAGtBPEDRpHkriON__b3KQ.jpg'),
  ('kaxoragylasm', 'dNWJCwQluEzrunBW7OUwJQ.png'),
  ('Saw them all', 'LGCaRifZ_ViRrpjT738yuQ.gif'),
  ('Be a tiger in the sack', 'lQzDpYYfHR3jclGRvj5jBg.png'),
  ('A Token of My Love', 'ZzcMZiY5TfcQn0r4unaOXw.png'),
  ('Look...Here', 'BuCMsTxBDjcZHy3Jm8O5yA.png'),
  ('bad email address', 'jpunVKetLYZDNfi61mL1QQ.gif'),
  ('Looking to get back into sh ape?', 'EkJuJwFTC3l8iUOPgDIxSg.gif'),
  ('Your heart beats over 100,000 times a day', 'CL_hSmBODogi0emwKlkddg.gif'),
  ('Guess what I got', 'mxAJT57D5bG5cEWibzfGlw.png'),
  ('Game Foot', 'SU6HvkSD9b7BAl0oEpxyXA.png'),
  ('Most guys dons''t have what it takes', 'iNNeAsrjpESuYoWer3cusA.png'),
  ('Why did you pick me?', 'fJQ2BAwvpE6NL26Eo4BbKg.png'),
  ('Erection for sexual activity', 'uIkYsNUixgYMyQtvW8VIDQ.png'),
  ('Fireman sidetrack', 'fcWQ3ZO6JajjqcOjhPboGQ.gif'),
  ('Never been easier', 'OLlu5pf_wxUSO11WyGoNzg.gif'),
  ('We''ll teach you how to behave in bed', 'l3fRck9r2oTBThLGbiffQA.jpg'),
  ('Impress your girl with plentiful explosions.', 'qC0p1Qp88qHYFCyKSST1Fw.jpg'),
  ('LOOK AT ME IM RICH', 'AcyUO85yi_zVdUlz0GV8xw.gif'),
  ('Found it, whoa', 'rU5zdQ5hFlfZiFChR2psFw.gif'),
  ('Prepare you left hand!', 'VTS0E_07CgKSv8O4lOOGiQ.png'),
  ('{?} {?} {?}. {?} {?}', 'xYHyFDSemaSoG7QCvhkmLw.png'),
  ('Feel 18th again', '8IVYONdc3ax36tVrVXXzXw.png'),
  ('Kya aap mere saath coffee peene chalenge?', 'LdhYBbBxVbVu5sg-3cJAFQ.jpg'),
  ('A Piece of Hawaii, Delivered to Your Door', 'q4W_FDzPMfd77rQeSBpNXA.png'),
  ('Your future, one-handed', 'fqcE2Upy5U0uKqGXUHW-Qg.jpg'),
  ('blockbuster casserole', 'FwhBasZSxWRExwWiZm-dIQ.jpg'),
  ('crematorium gladly', 'DBsBK_F2scXp-1Zy5eyTLg.png'),
  ('Bonus inches of pleasure', 'NJ11X28MpYGvKwx9fxnFsA.png'),
  ('prehistory planetarium', 'flZJiOV_MB6k3jgzl5cMvA.png'),
  ('Japanese hard with dildos', 'TyfmtBXUpFvnDG5tH9fj5w.png'),
  ('Notice: Your Online is Bloked!', 'PUqqzWYfjufqr_SOOL7vMQ.jpg'),
  ('Cuum for much longer with express herbals', 'JEk1t1-z7EtV2nAe403MOg.png'),
  ('100% off', 'yVqROWl_UcGeaFHi9E64Pw.png'),
  ('Retire a millionaire', 'iq4mfLxgXL9QritMd68-_w.png'),
  ('Canadian Pharmacy', '-y4fIVTIK0HKcxOsZCOqaA.png'),
  ('hi law', 'gXWfwo360L9AvcsX2R4xig.jpg'),
  ('/:A', 'MaLA4phldzgYjv8fVE45Dw.jpg'),
  ('Get a visit from the big dick fairy', 'LYYNzHm8nl-CUC6HLLOx9w.jpg'),
  ('Sex can', 'WhdMrWxn5xOlTPAzdSbWeg.png'),
  ('Get out of Debt Wizard', 'SLWOnd76TBJ2iv8H7uTHQQ.gif'),
  ('Toasty Atheism', 'dKzrPq9bKehImPZ0oHiVRA.gif'),
  ('Guess Who Is Coming to Town', 'p46MoCIra6KQCThUAunIFw.gif'),
  ('Let''s Hook Up Wednesday', '3eH0OJIIBNW8-Gy4nICPLg.jpg'),
  ('10 inch d_ck', 'VnGSiu77r5E_O5P-Weg2Qw.jpg'),
  ('Experience the feeling of youth again', 'hW2nqmgQphYy-ABPx_uYBg.jpg'),
  ('Gold and silver ores', 'CTTR3xr3Z5jgfXhpKhe-tg.png'),
  ('Oprah loves our cheese, and you will too', '5O6LZE-pwcKMsTjfdBAUDg.png'),
  ('gainlike', 'dYq0FJtYQVLWnSmZm5vSwA.png'),
  ('Madison strikes again', 'T0SOe4zq0riiVJck4KQXoA.png'),
  ('Perfect warning', 'b1bwl60qeCi8Se-XAlVd7A.png'),
  ('Worn out ticker?', 'YUP5IEvxx_WXDmNUaLV2rA.jpg'),
  ('ELIZABETH, SAVE 50% On Address Labels', 'O_M0lMSDqcO2zt8zkFtp3A.png'),
  ('Are you single and not exactly loving it?!', 'ifG2ybfgku8UagyW2giRxA.png'),
  ('Can Dr. Phil Save An Obese Baby?', 'BWfqMNv_qpMdT3Q7Kw4UYw.jpg'),
  ('Nazi Arcchitect?', 'fsQZHCTJkVqV2LSV0z4lJQ.jpg'),
  ('They dared me to do this. . .', 'XzGtWwQm_DbynJr54nanoA.png'),
  ('Video her coming over and over again', 'Y3FtG4YCuwlcCesym7S70w.jpg'),
  ('xwhatever', '-L_uTBpjYS4KWEbxqiErig.jpg'),
  ('children lessen risk', 'J_fm6sBBHVCtbb_ksP3hZg.jpg'),
  ('Dispute transaction', 'M0pZLOpM_SM1-EcmTHzOcw.jpg'),
  ('wowzers!', 'FrZGOa0Adv5m8BdD4vG2rg.png'),
  ('When boobs get this big', '79IYqUIkqAmhaTAmCuCQNw.jpg'),
  ('catharsius cathartae cathartes', 'VhR16J6v0d4o8uA_TIowwg.png'),
  ('qpotato', 'wVUu0rVfqAZBAtlTSITHWg.jpg'),
  ('Don''t be embarassed, we are here to help. Nazi', '4nPlEKWWr-9wOwj89zdi5Q.png'),
  ('Everything''s canceled today', 'adYZIfATv1WqngLAE0xj4Q.png'),
  ('Omgninjers', 'V-KV7avfFzLe3yrCILMb_w.png'),
  ('Try a sample of Olay Body Firming Reviver Body Lotion for Nicole Wexler', 'FJ06Xza9uqO0cvLYYAuMZA.jpg'),
  ('Hot women are waiting on you!', 'OyKVGuwtr8OIr7RTZatb0Q.png'),
  ('You''ll Be Set This Holiday Season', 'jkabJX6y8cnBv335MwtB1w.jpg'),
  ('ARE YOU DEAD OR ALIVE? PLEASE RESPOND', 'kwGDKrZuIa4jenVU349Sew.png'),
  ('I feel this is Murder', 'n4ycBrBjsi-CGNpgyE50Pw.gif'),
  ('Cadave''r', 'nwbS8EN64IOi1Mo0fM9f7w.jpg'),
  ('Passion: Approved', 'vZ0o0VwYxCHvYl1-9qLBdQ.gif'),
  ('I''d hit it .. Twice', '22ZpuFb7VIMiS2QdGnx8ig.jpg'),
  ('Just do her.', 'I1DbgYvUAX1JyJa9LY6rAA.gif'),
  ('Louis Vuitton bags and Franck Muller watches', 'zZGkY1EBnsVJ6zvDFsnCSg.png'),
  ('Pink, wet, and shaven.', 'NIM0mVWQi7r80xrjI2O1aw.png'),
  ('Pain is temporary, victory is forever.', '9_swgQ9yfI5e08chQ1nZ8Q.png'),
  ('Jeremiah', 'R_QnJe0DVG8UmnlFw81jUQ.png'),
  ('fwd: FWD: children with cancer', '5QTHGOlNhdrS8HkvXvqW1g.png'),
  ('Because of a bet.', 'u3EuZsDmz7g-oQBcKNjJXQ.png'),
  ('Longer harder fiercer bangs', 'FfGc0aDs6t4eoCj5Yh3myQ.png'),
  ('CONGRAT!!!!!!!', '0S8u_XlggkrqBqVYf5EmJg.png'),
  ('Wanna change ur habits', '5QjUhZ2RHTlsb6tt8P4-rg.png'),
  ('You have until Friday', 'IrDE4VqE6p8ybsrnY2bOCw.png'),
  ('You need to improve your little friend', 'qpleqOHpL8Z1n4h9-Kf8hw.png'),
  ('What happened to tiger?', 'rwH1T39qCBOU1g8_ZBARCg.jpg'),
  ('Enjoy Your Life with the Patch', 'WqcMvRQQuHB-0oi7QfCTbA.jpg'),
  ('HOW CIA SPIES MASTER 7 LANGUAGES', 'EjIRkhy48Hr6EQgNpvCkeQ.jpg'),
  ('She was so tight', 'w1AEAOSwKU46nad7g_HPng.png'),
  ('Good alone. Even better together.', '1ZgxW_SVgk5_qg_GzH2hSQ.gif'),
  ('lengthanderection', 'BQs1qvBGwfh4b3lqrq_TZQ.jpg'),
  ('nanan', 'iehaEJx3eggYnkKqEVlUnA.png'),
  ('Bondage oopsie', 'P72xGnxaSlyBjJ4V0i4gLg.jpg'),
  ('Do You Like Ice Cream? Come & Get Some!', 'Y1iUbCgh7QPgbVwuJmH3fA.gif'),
  ('It does not matter what you write.', 'HRRU1ouNptKbBdsICZUM8w.png'),
  ('Face it, you''re soft', 'NJJfkkmCbSg-vwQYWmlOPQ.png'),
  ('Boa then were silent.', 'z37fzWfjC9M2wZJpMd6aHw.jpg'),
  ('KickAss Watchs', 'niFKPBUNfWzP-LLGLjuEbQ.png'),
  ('Darling, you look good enough to eat', 'wNSVnUQd-9owUMgjTiAk4g.png'),
  ('Celebrated release', 'XNHsEmt_HLcIbVczga9Olg.jpg'),
  ('ci@lis', 'AKnNxEkn4gAK-qoERpTLFQ.png'),
  ('It is still bikini season', 'PlP9KObPCdXsoDH2_ycF8Q.jpg'),
  ('Patrick Curl is now following you on Twitter!', 'HUvv4459pTWmCELP7I7fnw.gif'),
  ('B..e..s..t. R..e..p..l..i..c..a..s.....', '0UF7Teup-Op4DMvwNi6pSg.png'),
  ('exodus senior Crows', 'cX_YTQyoKyXTF0rctqw07A.jpg'),
  ('(no subject)', 'w9pYyU6IDY0fIs-6yJ_-ng.gif'),
  ('dockyard', 'C8SNUi5hQpIcjNRGBZDHsg.jpg'),
  ('Your easy way to become well hung', '1cHJsLfLLBjz-0V8rIxgiQ.jpg'),
  ('Teen getting anal outdoor', 'FpcYZzTOXPNG0WDd-BdpMA.jpg'),
  ('blau', 'tK1D9r0mkGaT0uk2KQEOTQ.png'),
  ('The Secret is Out! Grants are Free!', 'aiWe_sb-ATWfuDyInMcTIQ.png'),
  ('suicidal', 'HRKw0hF3UviYW22mr1oYtw.png'),
  ('For Erotic Offline Encounters!', 'QOrMkJC-qmawaAf3rdLE7g.jpg'),
  ('80d', 'Aynz00JnQcjRwd1LTtBGbQ.jpg'),
  ('Dressing to impress pyrometer falcon', 'tlxUPYQsM9D7ExtWr35s6A.png'),
  ('take her from behind', 'Dq0v2_Z95vTofNAez56Wnw.png'),
  ('1 2 3 4 WE HAVE YOUR CREDIT SCORE ! ! ! ! !', 'k4FPsU1MDdJPMZe-zR6gVQ.jpg'),
  ('You Need It Now', 'bTT07Z_58z4MfUO0KUeFwg.png'),
  ('Do not see if you''re a lady', 'sBkfJU0AO189CA3Mo084Lw.png'),
  ('no escape', 'k-Kq978sHD_RRyQ1CtzAOg.png'),
  ('Big white rock hard meat', '1M6qPYiqNLSPL_w4pApxPw.jpg'),
  ('My penis hurts after a big session', 'cBwEH8q0N3ndr2SpxfRPLQ.gif'),
  ('hate condoms?', 'eKiuLUGf07tD3oZZ1glquQ.jpg'),
  ('Electronic!!!Mail!!!Award!!!Winning!!!Notification', 'F-RDEzUcGo0teEcIensbBA.gif'),
  ('With a cool watch you can beat everybody.', 'TtKfqhmp28eCIHYhEBtz4A.jpg'),
  ('YOUR EMAIL WON THE LOTTER', 'jYmx2QC8QkwDdSDrup8f6Q.png'),
  ('Drop 20 lbs for summer', 'OwbL-uOtsHlEHmoHufEdeQ.PNG'),
  ('omega james bond seamaster - black with black bezel, SS band', 'xDKBUW38rFd2hrnteD27DQ.jpg'),
  ('This is how you become a CSI. Get your Forensics Degree.', 'SgWovHk5ePFwN63l9qKQOg.jpg'),
  ('Milk her for everything', 'c-5tPWf_NV7XCWOBE42_nQ.jpg'),
  ('Ferdinand''s problem', 'PUXMjvPcCT1My0uUmNuEHg.png'),
  ('Low cost seductive accessories', 'XkzZEFhu1Mix3v1RQXKeGg.png'),
  ('It''s a lazzy Sunday', '50q132_qMikjNlvqoaT6OA.gif'),
  ('On our way to a fire, are we?', '39VwPfhy1cMYXssusB2wYg.png'),
  ('Save thousands, no one will ever know.', 'wk5E6cVBKdm1NtQorjreow.jpg'),
  ('unfair', 'rfBiL5l-HfmDDGlsblTU6Q.jpg'),
  ('Be her mighty night predator', 'G8iPtSZDvzU9FxbfizugpQ.png'),
  ('Note from the desk of Pat Sajak:', 'TUmHAwtR8d8wwbPzOHaiog.gif'),
  ('Contact Mr. Gregory Hats', 'RZXku1DZzTQUaHGxm36oPQ.png'),
  ('heterocycle', 'vZ4r83rnnpafGtdT4jYQFA.png'),
  ('LETTER !', '6UeKS8_OaENG5CuLqUaaEw.png'),
  ('Sharp, professional  and honest', 'SNR7C9CSDklPM_x8ZzYh5w.png'),
  ('pistachio', 'A33LQ2NfeTjbLQogAUPufQ.jpg'),
  ('Tide to Go', 'OjAz_FXINHKdaLc0ZPaj-g.jpg'),
  ('Ultimate symbols of status', 'IQHACZEk30wNAtXc4668rg.png'),
  ('Complimentary Chewing Gum Samples', '_H1Tps_6ZUHx6Mf1jD0nbg.png'),
  ('titan poker', 'OoDPPBdQklETP0uoduozjw.png'),
  ('That''s why I hike with poles', 'IybM-etyArSORqjQ9tdJbA.png'),
  ('Dick in pussy', 'sUFvHX2nR6nps8uhrwdrlA.gif'),
  ('The trend continued this year', 'v0SDRnpCKvsMEYWphBAMpA.png'),
  ('Big boobed secretary stripping stop', 'QOXWmkMkkn4nS0320rR7tg.png'),
  ('subordination', '3GpV8vqGouZ_PQOoTrz62w.gif'),
  ('your cat, please', 'NTxv1ZVs8xVrz7Xlv2psMA.gif'),
  ('PLEASE GET BACK TO ME', 'TmEw_Rh4Hc_dqde-e9-dDw.gif'),
  ('Do not make eye contact.', 'RE5MJmgpWIXXzc_C0D-AZg.png'),
  ('Some teacher', '_7FjjRL2rF9SEVaNqGM4EA.png'),
  ('Mac or PC', 'h37y_qERcTaqsevTMVJIGA.png'),
  ('wanna impress ur GF', 'zzHUIjoSj0f0gJsrpsxCcg.gif'),
  ('an URGENT letter from nigeria', 'fkSfDMdFON0H5HcHHmz8dw.jpg'),
  ('She revealed herself to me', 'ESNjUIGSaUlsIGm-M8bVfA.jpg'),
  ('Wow...Nice Body', '7E6zlr41Pn5YQSVx6fAhOg.jpg'),
  ('Britannia waived the rules!', 'gJHr-iV2NmA-npO_RSw2Jw.jpg'),
  ('Expel Disgusting Fats', 'dhzKqAjpzgIuOpLFejvfmA.jpg'),
  ('Hörny HouseWïfe', 'oJWuVK6cTGg14LXIKwABWw.gif'),
  ('$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$', '81chs_94hy5mUoaX50fUvQ.jpg'),
  ('A Permanent Solution for Hair Loss', 'fTFnlmNckaKS_RQIyudQtw.png'),
  ('Lets ScrewOur Brains Out', '0Ljkv63Qi2JNSWWpsQjPhg.png'),
  ('Separate yourself from other men', '4wtrDkElGHA66tDgTNEfaw.png'),
  ('Einstein''s Twin Paradox Finally Solved', '8Qm2jFRdEybtMjvnEPEGyQ.gif'),
  ('Weapon Diamond Bomb Pillow Stomach Typewriter Book', 'XJBvGMN4T3l5mDzU2pCL3Q.jpg'),
  ('Pharm trade', 'fZof_xnqULlGVcXjupPsDw.png'),
  ('cunninglingus strategy', 'jWJ31cHZNlBa44L2WI_9yg.png'),
  ('WeShould HookUp ForSex', 'untT-l-yw6Z7iDmEkaktOg.gif'),
  ('Re: Haha, help is here', 'a_dILouB-ImXADLKSfmiKg.jpg')
;

UPDATE comics
SET alt_image = 'XzGtWwQm_DbynJr54nanoA.alt.png'
WHERE title = 'They dared me to do this. . .';
